"""create voice_embeddings table

Revision ID: b3279f4f4323
Revises: 
Create Date: 2025-08-05 10:25:44.074650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3279f4f4323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_embeddings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_voice_embeddings_user_id'), 'voice_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_embeddings_user_id'), table_name='voice_embeddings')
    op.drop_table('voice_embeddings')
    # ### end Alembic commands ###
